### ISSUE TITLE
Transaction for 42000000000 is greater than spendable balance of 0

### ISSUE THREAD

**Issue by johnathon-b** [Yakuhito/tibet#11]
Each time I try to create-pair or  launch-test-token I receive errors such as the followings:

create-pair
```
ValueError: {'error': 'Transaction for 42000000000 is greater than spendable balance of 0. There may be other transactions pending or our minimum coin amount is too high.', 'success': False, 'traceback': 'Traceback (most recent call last):\n  File "chia/rpc/util.py", line 21, in inner\n  File "chia/rpc/util.py", line 82, in rpc_endpoint\n  File "chia/rpc/wallet_rpc_api.py", line 1173, in select_coins\n  File "chia/wallet/wallet.py", line 256, in select_coins\n  File "chia/wallet/coin_selection.py", line 57, in select_coins\nValueError: Transaction for 42000000000 is greater than spendable balance of 0. There may be other transactions pending or our minimum coin amount is too high.\n'}```

launch-test-token
```
ValueError: {'error': 'Transaction for 1000000000 is greater than spendable balance of 0. There may be other transactions pending or our minimum coin amount is too high.', 'success': False, 'traceback': 'Traceback (most recent call last):\n  File "chia/rpc/util.py", line 21, in inner\n  File "chia/rpc/util.py", line 82, in rpc_endpoint\n  File "chia/rpc/wallet_rpc_api.py", line 1173, in select_coins\n  File "chia/wallet/wallet.py", line 256, in select_coins\n  File "chia/wallet/coin_selection.py", line 57, in select_coins\nValueError: Transaction for 1000000000 is greater than spendable balance of 0. There may be other transactions pending or our minimum coin amount is too high.\n'}
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x110989c90>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x1131318d0>, 493053.276296166)]']
connector: <aiohttp.connector.TCPConnector object at 0x11316e950>
```

Chia Wallet: 2.0.0
Full Node: Fire Academy API Token
tibet: main branch

**Comment by Yakuhito** [comment]
Hey there! I did some testing with the local simulator and couldn't reproduce this issue. Could you please run `chia wallet show` and select your fingerprint (i.e., make sure you're logged in to the right wallet), send your total XCH balance to yourself (to make sure there are no 0.042 XCH coins), and try again? I can launch the pool for you (DM on twitter), but I'd like to have this fixed so others don't encounter it.

**Comment by Yakuhito** [comment]
Hey, I managed to reproduce! The problem was that my wallet was using `2.1.1` while the local installation of Tibet was using `2.0` - I just pushed a commit that upgrades everything and accounts fro breaking changes. I think everything should work now; please let me know if there are any more issues

**Comment by johnathon-b** [comment]
This has solved the issue. It seems to be working now!
